[pytest]
cache_dir = /tmp/.pytest_cache
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
filterwarnings =
    error::ResourceWarning
    error::pytest.PytestUnraisableExceptionWarning
    ignore::DeprecationWarning:fastapi
    ignore:Using `httpx` with `starlette.testclient` is deprecated
    ignore::DeprecationWarning:websockets.legacy
    ignore::DeprecationWarning:uvicorn.protocols.websockets.websockets_impl
    ignore::DeprecationWarning:websockets.exceptions
    ignore:unclosed database:ResourceWarning
    ignore:unclosed database:pytest.PytestUnraisableExceptionWarning
