[pytest]
cache_dir = /tmp/.pytest_cache
asyncio_mode = auto
filterwarnings =
    ignore::DeprecationWarning:fastapi
    ignore:Using `httpx` with `starlette.testclient` is deprecated
    ignore::DeprecationWarning:websockets.legacy
    ignore::DeprecationWarning:uvicorn.protocols.websockets.websockets_impl
