#!/bin/bash
# OneClaw Wizard Deployment Script
# Called by setup-wizard.html to automatically deploy OneClaw

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPT_DIR"

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Parse arguments
AI_PROVIDER=""
API_KEY=""
TELEGRAM_TOKEN=""
ENABLE_TAILSCALE=false

while [[ $# -gt 0 ]]; do
    case $1 in
        --provider)
            AI_PROVIDER="$2"
            shift 2
            ;;
        --api-key)
            API_KEY="$2"
            shift 2
            ;;
        --telegram)
            TELEGRAM_TOKEN="$2"
            shift 2
            ;;
        --tailscale)
            ENABLE_TAILSCALE=true
            shift
            ;;
        *)
            shift
            ;;
    esac
done

echo -e "${BLUE}🦞 OneClaw Wizard Deployment${NC}"
echo ""

# Step 1: Create secrets file
echo -e "${BLUE}[1/5]${NC} Creating secrets file..."
mkdir -p oneclaw-container/secrets
cat > oneclaw-container/secrets/.env << EOF
# OneClaw Secrets - Generated by Setup Wizard
# DO NOT COMMIT THIS FILE TO GIT

# Gateway Authentication
OPENCLAW_GATEWAY_TOKEN=$(openssl rand -hex 32)

# AI Provider API Key
EOF

if [ "$AI_PROVIDER" = "openai" ]; then
    echo "OPENAI_API_KEY=$API_KEY" >> oneclaw-container/secrets/.env
elif [ "$AI_PROVIDER" = "anthropic" ]; then
    echo "ANTHROPIC_API_KEY=$API_KEY" >> oneclaw-container/secrets/.env
fi

if [ -n "$TELEGRAM_TOKEN" ]; then
    echo "" >> oneclaw-container/secrets/.env
    echo "# Telegram Bot" >> oneclaw-container/secrets/.env
    echo "TELEGRAM_BOT_TOKEN=$TELEGRAM_TOKEN" >> oneclaw-container/secrets/.env
fi

chmod 600 oneclaw-container/secrets/.env
echo -e "${GREEN}✓${NC} Secrets file created"
echo ""

# Step 2: Update config for AI provider
echo -e "${BLUE}[2/5]${NC} Configuring AI model..."
CONFIG_FILE="oneclaw-container/config/config.json"

if [ "$AI_PROVIDER" = "openai" ]; then
    # Update model to use OpenAI
    if [ -f "$CONFIG_FILE" ]; then
        # Use sed to replace the model
        sed -i '' 's/"model": "anthropic\/claude-opus-4-6"/"model": "openai\/gpt-4"/g' "$CONFIG_FILE"
        echo -e "${GREEN}✓${NC} Configured for OpenAI GPT-4"
    fi
else
    echo -e "${GREEN}✓${NC} Configured for Anthropic Claude"
fi
echo ""

# Step 3: Start Docker container
echo -e "${BLUE}[3/5]${NC} Starting OneClaw container..."

# Check if Docker is running
if ! docker info > /dev/null 2>&1; then
    echo -e "${RED}✗${NC} Docker is not running!"
    echo "Please start Docker Desktop or OrbStack and try again."
    exit 1
fi

# Start container
cd oneclaw-container
docker compose up -d
cd ..

# Wait for container to be healthy
echo "Waiting for container to start (30 seconds)..."
sleep 30

# Check if container is running
if docker ps | grep -q oneclaw_isaiah; then
    echo -e "${GREEN}✓${NC} Container started successfully"
else
    echo -e "${RED}✗${NC} Container failed to start"
    echo "Check logs with: docker compose -f oneclaw-container/docker-compose.yml logs"
    exit 1
fi
echo ""

# Step 4: Start web interface
echo -e "${BLUE}[4/5]${NC} Starting web interface..."

# Kill any existing web server on port 18791
if lsof -ti:18791 > /dev/null 2>&1; then
    kill $(lsof -ti:18791) 2>/dev/null || true
    sleep 2
fi

# Start web server
nohup python3 -m http.server 18791 --directory oneclaw-container/control-ui > /tmp/oneclaw-webserver.log 2>&1 &

sleep 3

# Verify web server started
if curl -s http://localhost:18791/ > /dev/null; then
    echo -e "${GREEN}✓${NC} Web interface started on http://localhost:18791"
else
    echo -e "${YELLOW}⚠${NC} Web interface may not have started"
    echo "Check logs at: /tmp/oneclaw-webserver.log"
fi
echo ""

# Step 5: Configure Tailscale (optional)
if [ "$ENABLE_TAILSCALE" = true ]; then
    echo -e "${BLUE}[5/5]${NC} Configuring Tailscale..."

    if command -v tailscale &> /dev/null; then
        # Stop any existing serve
        tailscale serve --https=443 off 2>/dev/null || true

        # Start Tailscale serve
        TAILSCALE_OUTPUT=$(tailscale serve --bg http://127.0.0.1:18791 2>&1)
        TAILSCALE_URL=$(echo "$TAILSCALE_OUTPUT" | grep -o 'https://[^/]*\.ts\.net/')

        if [ -n "$TAILSCALE_URL" ]; then
            echo -e "${GREEN}✓${NC} Tailscale configured: $TAILSCALE_URL"
            echo "$TAILSCALE_URL" > /tmp/oneclaw-tailscale-url.txt
        else
            echo -e "${YELLOW}⚠${NC} Tailscale configuration incomplete"
        fi
    else
        echo -e "${YELLOW}⚠${NC} Tailscale not installed - skipping"
    fi
else
    echo -e "${BLUE}[5/5]${NC} Tailscale setup skipped"
fi
echo ""

# Final summary
echo -e "${GREEN}╔════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║  OneClaw Deployment Complete! 🎉                      ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════╝${NC}"
echo ""
echo "Access OneClaw:"
echo "  🌐 Local:  http://localhost:18791"
if [ "$ENABLE_TAILSCALE" = true ] && [ -f /tmp/oneclaw-tailscale-url.txt ]; then
    echo "  🔒 Remote: $(cat /tmp/oneclaw-tailscale-url.txt)"
fi
echo ""
echo "Connection details:"
echo "  Gateway URL: ws://127.0.0.1:18789"
echo "  Auth Token:  $(grep OPENCLAW_GATEWAY_TOKEN oneclaw-container/secrets/.env | cut -d'=' -f2)"
echo ""
echo "Management:"
echo "  Start:  ./start-oneclaw.sh"
echo "  Stop:   ./stop-oneclaw.sh"
echo "  Logs:   docker compose -f oneclaw-container/docker-compose.yml logs -f"
echo ""
echo "Next: Open http://localhost:18791 in your browser and start chatting!"
echo ""

# Return success
exit 0
