# Copyright © 2026 Isaiah Dallas Jefferson, Jr. AgentShroud™. All rights reserved.
# AgentShroud™ is a trademark of Isaiah Dallas Jefferson, Jr. (USPTO Serial No. 99728633)
"""GENERATED FILE — do not hand-edit.

Feed-source hostnames derived from ~/Development/feeds/feeds.yaml (the
single source of truth for the Feedbin/Daily-Brief workstream). Regenerate
after any manifest change with:

  docker exec -i agentshroud-hermes-v2 python3 \
    /opt/data/skills/media/feedbin/scripts/feedbin.py hosts - \
    < ~/Development/feeds/feeds.yaml   # then paste into FEED_HOSTS below
  (or run scripts from the feeds repo README)

Consumed by egress_config.PERMANENT_EGRESS_DOMAINS so full-article
fetches for top Daily-Brief clusters are allowlisted without hand
maintenance. Generated 2026-08-29 from the 17-topic manifest.
"""

FEED_HOSTS: list[str] = [
    "9to5mac.com",
    "api.quantamagazine.org",
    "arrow.apache.org",
    "aws.amazon.com",
    "beckyhansmeyer.com",
    "blog.google",
    "boingboing.net",
    "brew.sh",
    "bringatrailer.com",
    "calnewport.com",
    "cate.blog",
    "cloudblog.withgoogle.com",
    "conda-forge.org",
    "daringfireball.net",
    "david-smith.org",
    "developer.apple.com",
    "developers.googleblog.com",
    "eclecticlight.co",
    "electrek.co",
    "embracethered.com",
    "ericasadun.com",
    "feeds.arstechnica.com",
    "feeds.bbci.co.uk",
    "feeds.content.dowjones.io",
    "feeds.feedburner.com",
    "feeds.finance.yahoo.com",
    "feeds.kottke.org",
    "feeds.macrumors.com",
    "feeds.npr.org",
    "furbo.org",
    "gettingthingsdone.com",
    "github.blog",
    "github.com",
    "heatmap.news",
    "hnrss.org",
    "huggingface.co",
    "iceberg.apache.org",
    "idallasj.github.io",
    "importai.substack.com",
    "inessential.com",
    "insideevs.com",
    "ir.fluenceenergy.com",
    "itsfoss.com",
    "jvns.ca",
    "krebsonsecurity.com",
    "lwn.net",
    "mjtsai.com",
    "news.google.com",
    "news.risky.biz",
    "newsroom.porsche.com",
    "nnw.ranchero.com",
    "obsidian.md",
    "onefoottsunami.com",
    "openai.com",
    "pi-hole.net",
    "podnews.net",
    "postgresweekly.com",
    "pv-magazine-usa.com",
    "pythoninsider.blogspot.com",
    "realpython.com",
    "rennlist.com",
    "rosemaryorchard.com",
    "rss.nytimes.com",
    "shapeof.com",
    "simonwillison.net",
    "sixcolors.com",
    "stratechery.com",
    "tailscale.com",
    "teslamotorsclub.com",
    "therecord.media",
    "thesweetsetup.com",
    "tidbits.com",
    "towardsdatascience.com",
    "vincode.io",
    "wtop.com",
    "www.apple.com",
    "www.canarymedia.com",
    "www.caranddriver.com",
    "www.cisa.gov",
    "www.cnbc.com",
    "www.cybertruckownersclub.com",
    "www.databricks.com",
    "www.deeplearning.ai",
    "www.devontechnologies.com",
    "www.dragos.com",
    "www.energy-storage.news",
    "www.energy.gov",
    "www.espn.com",
    "www.hagerty.com",
    "www.home-assistant.io",
    "www.interconnects.ai",
    "www.latent.space",
    "www.latitudemedia.com",
    "www.linuxtoday.com",
    "www.macsparky.com",
    "www.macstories.net",
    "www.manton.org",
    "www.notateslaapp.com",
    "www.phoronix.com",
    "www.python.org",
    "www.raspberrypi.com",
    "www.raycast.com",
    "www.reddit.com",
    "www.roadandtrack.com",
    "www.schneier.com",
    "www.sciencefriday.com",
    "www.tdworld.com",
    "www.teslarati.com",
    "www.thedrive.com",
    "www.theguardian.com",
    "www.theregister.com",
    "www.theringer.com",
    "www.thisiscolossal.com",
    "www.utilitydive.com",
    "www.volts.wtf",
    "xkcd.com",
]
