#!/bin/bash
# ============================================================
# AgentShroud Multi-Instance Launcher
# ============================================================
# Launches a new AgentShroud instance on available ports
# with Tailscale serve configured for HTTPS access.
#
# Usage: ./scripts/launch-instance.sh [instance_name]
# Example: ./scripts/launch-instance.sh test-v2
# ============================================================

set -euo pipefail

export PATH="/usr/local/bin:/opt/homebrew/bin:$PATH"
export DOCKER_HOST="${DOCKER_HOST:-unix:///Users/ijefferson.admin/.docker/run/docker.sock}"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
INSTANCE_NAME="${1:-agentshroud-$(date +%Y%m%d-%H%M%S)}"
COMPOSE_DIR="$PROJECT_DIR/docker"

echo "🚀 AgentShroud Multi-Instance Launcher"
echo "======================================="
echo "Instance: $INSTANCE_NAME"
echo ""

# --- Find available ports ---
echo "🔍 Scanning for available ports..."

find_port() {
    local start=$1
    local port=$start
    while [ $port -lt 65000 ]; do
        if ! netstat -an 2>/dev/null | grep -q "[:.]${port} .*LISTEN" && \
           ! lsof -nP -iTCP:$port -sTCP:LISTEN >/dev/null 2>&1; then
            echo $port
            return
        fi
        port=$((port + 1))
    done
    echo ""
}

GATEWAY_PORT=$(find_port 9000)
PROXY_PORT=$(find_port $((GATEWAY_PORT + 1)))

if [ -z "$GATEWAY_PORT" ] || [ -z "$PROXY_PORT" ]; then
    echo "❌ Could not find available ports"
    exit 1
fi

echo "   Gateway API:  $GATEWAY_PORT"
echo "   HTTP Proxy:   $PROXY_PORT"
echo ""

# --- Create instance-specific compose override ---
OVERRIDE_FILE="$COMPOSE_DIR/docker-compose.${INSTANCE_NAME}.yml"

cat > "$OVERRIDE_FILE" << EOF
# Auto-generated by launch-instance.sh
# Instance: $INSTANCE_NAME
# Created: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

services:
  agentshroud-gateway:
    container_name: ${INSTANCE_NAME}-gateway
    ports:
      - "127.0.0.1:${GATEWAY_PORT}:8080"
    environment:
      - INSTANCE_NAME=${INSTANCE_NAME}

  agentshroud-openclaw:
    container_name: ${INSTANCE_NAME}-bot
    environment:
      - INSTANCE_NAME=${INSTANCE_NAME}

networks:
  agentshroud-isolated:
    name: ${INSTANCE_NAME}-isolated
  agentshroud-internal:
    name: ${INSTANCE_NAME}-internal
EOF

echo "📄 Created compose override: $OVERRIDE_FILE"

# --- Build and launch ---
echo ""
echo "🔨 Building containers..."
cd "$COMPOSE_DIR"

COMPOSE_PROJECT_NAME="$INSTANCE_NAME" docker compose \
    -f docker-compose.yml \
    -f "docker-compose.${INSTANCE_NAME}.yml" \
    build 2>&1 | tail -5

echo ""
echo "🚀 Starting instance..."
COMPOSE_PROJECT_NAME="$INSTANCE_NAME" docker compose \
    -f docker-compose.yml \
    -f "docker-compose.${INSTANCE_NAME}.yml" \
    up -d 2>&1

echo ""
echo "⏳ Waiting 15 seconds for startup..."
sleep 15

# --- Check health ---
echo ""
echo "🏥 Health check..."
COMPOSE_PROJECT_NAME="$INSTANCE_NAME" docker compose \
    -f docker-compose.yml \
    -f "docker-compose.${INSTANCE_NAME}.yml" \
    ps --format "table {{.Name}}\t{{.Status}}\t{{.Ports}}"

# --- Tailscale serve ---
echo ""
echo "🌐 Configuring Tailscale serve..."

# Serve gateway on HTTPS via Tailscale
if command -v tailscale >/dev/null 2>&1; then
    tailscale serve --bg --https=${GATEWAY_PORT} http://127.0.0.1:${GATEWAY_PORT} 2>&1 && \
        echo "   ✅ Gateway: https://$(tailscale status --self --json 2>/dev/null | python3 -c 'import sys,json; print(json.load(sys.stdin)["Self"]["DNSName"].rstrip("."))'):${GATEWAY_PORT}" || \
        echo "   ⚠️  Tailscale serve failed — gateway available at http://127.0.0.1:${GATEWAY_PORT}"
else
    echo "   ⚠️  Tailscale CLI not found — gateway available at http://127.0.0.1:${GATEWAY_PORT}"
fi

# --- Summary ---
echo ""
echo "============================================"
echo "✅ Instance '$INSTANCE_NAME' is running!"
echo "============================================"
echo ""
echo "   Gateway API:  http://127.0.0.1:${GATEWAY_PORT}"
echo "   HTTP Proxy:   http://127.0.0.1:${PROXY_PORT}"
echo "   Override:     $OVERRIDE_FILE"
echo ""
echo "   Manage:"
echo "     Status:  COMPOSE_PROJECT_NAME=$INSTANCE_NAME docker compose -f docker-compose.yml -f docker-compose.${INSTANCE_NAME}.yml ps"
echo "     Logs:    COMPOSE_PROJECT_NAME=$INSTANCE_NAME docker compose -f docker-compose.yml -f docker-compose.${INSTANCE_NAME}.yml logs -f"
echo "     Stop:    COMPOSE_PROJECT_NAME=$INSTANCE_NAME docker compose -f docker-compose.yml -f docker-compose.${INSTANCE_NAME}.yml down"
echo "     Remove:  rm $OVERRIDE_FILE"
echo ""
echo "   Rollback (if lockdown breaks things):"
echo "     $SCRIPT_DIR/emergency-rollback.sh"
