#!/usr/bin/env bash
# Copyright © 2026 Isaiah Dallas Jefferson, Jr. AgentShroud™. All rights reserved.
# AgentShroud™ is a trademark of Isaiah Dallas Jefferson, Jr. (USPTO Serial No. 99728633)
# Patent Pending — U.S. Provisional Application No. 64/018,744
#
# scripts/validate-skills-manifest.sh — CI gate: verify deployed manifests match source.
#
# Reads the canonical manifest from ~/.llm_settings/manifest.json (generated by
# sync-llm-settings.sh) and compares hashes against the deployed manifest.json in
# each bot config directory.
#
# Exits non-zero if any hash drift is detected. Used as a CI gate — if the canonical
# ~/.llm_settings/ tree changes without a corresponding sync + commit, CI fails.
#
# USAGE:
#   bash scripts/validate-skills-manifest.sh [--source DIR]
#
#   --source DIR    Override source (default: ~/.llm_settings)
#
# EXIT CODES:
#   0 — all destinations match the canonical manifest (no drift)
#   1 — drift detected, or source manifest missing
#   2 — argument error

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$SCRIPT_DIR/.." && pwd)"

# ── Defaults ─────────────────────────────────────────────────────────────────
SOURCE="${HOME}/.llm_settings"

# ── Argument parsing ─────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case "$1" in
    --source)
      SOURCE="$2"; shift 2 ;;
    *)
      echo "ERROR: Unknown argument: $1" >&2
      echo "Usage: $0 [--source DIR]" >&2
      exit 2 ;;
  esac
done

# ── SHA-256 helper (macOS + Linux) ────────────────────────────────────────────
_sha256() {
  local file="$1"
  if command -v sha256sum &>/dev/null; then
    sha256sum "$file" | awk '{print $1}'
  else
    shasum -a 256 "$file" | awk '{print $1}'
  fi
}

# ── Validate source ──────────────────────────────────────────────────────────
if [[ ! -d "$SOURCE" ]]; then
  echo "ERROR: Source directory not found: ${SOURCE}" >&2
  exit 1
fi

# ── Destinations ─────────────────────────────────────────────────────────────
# SKILLGUARD_TEST_DEST_ROOT is a test-only hook (see sync-llm-settings.sh) that
# redirects both bot destinations under a temp dir. Unset in production.
if [[ -n "${SKILLGUARD_TEST_DEST_ROOT:-}" ]]; then
  declare -a DESTINATIONS=(
    "${SKILLGUARD_TEST_DEST_ROOT}/openclaw"
    "${SKILLGUARD_TEST_DEST_ROOT}/hermes"
  )
else
  declare -a DESTINATIONS=(
    "${REPO}/docker/config/openclaw"
    "${REPO}/docker/config/hermes"
  )
fi

echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║  AgentShroud™ — Skills Manifest Validation           ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""

overall_drift=0

for dest in "${DESTINATIONS[@]}"; do
  echo "── Checking: ${dest}"
  dest_manifest="${dest}/manifest.json"

  if [[ ! -f "$dest_manifest" ]]; then
    echo "  FAIL: manifest.json not found — run scripts/sync-llm-settings.sh first" >&2
    overall_drift=1
    continue
  fi

  # Extract entries from deployed manifest.json using python3
  drift_names="$(python3 - "$SOURCE" "$dest_manifest" <<'PYEOF'
import json, hashlib, sys
from pathlib import Path

source = Path(sys.argv[1])
manifest_path = Path(sys.argv[2])

with open(manifest_path) as f:
    data = json.load(f)

drifted = []
for entry in data.get("entries", []):
    name = entry["name"]
    expected_hash = entry["hash"]
    deployed_file = Path(sys.argv[2]).parent / name

    if not deployed_file.exists():
        drifted.append(f"MISSING:{name}")
        continue

    actual_hash = hashlib.sha256(deployed_file.read_bytes()).hexdigest()
    if actual_hash != expected_hash:
        drifted.append(f"HASH_MISMATCH:{name}")

for d in drifted:
    print(d)
PYEOF
)"

  if [[ -z "$drift_names" ]]; then
    echo "  OK: all entries match"
  else
    echo "  FAIL: drift detected:" >&2
    while IFS= read -r line; do
      echo "    $line" >&2
    done <<< "$drift_names"
    overall_drift=1
  fi
  echo ""
done

echo "══════════════════════════════════════════════════════"
if [[ "$overall_drift" -eq 0 ]]; then
  echo "  Result: PASS — all destinations in sync"
  echo "══════════════════════════════════════════════════════"
  echo ""
  exit 0
else
  echo "  Result: FAIL — drift detected in one or more destinations" >&2
  echo "  Run: bash scripts/sync-llm-settings.sh" >&2
  echo "══════════════════════════════════════════════════════"
  echo ""
  exit 1
fi
