#!/bin/bash
#
# Install git hooks to a repository — ADDITIVELY.
#
# Usage: ./install.sh [--global] [--force]
#
# WHY THIS SCRIPT NO LONGER COPIES A HOOK OVER .git/hooks/pre-commit
# ------------------------------------------------------------------
# It used to do exactly that (`cp "$HOOK_SOURCE" .git/hooks/pre-commit`), plus
# `git secrets --install --force`. Both write the SAME single file, so whichever
# ran last silently won. On agentshroud that cost real coverage: a bare
# `git secrets --install` had reduced .git/hooks/pre-commit to a two-line
# git-secrets call, so gitleaks, detect-secrets, ruff, black and semgrep ran on
# no commit at all — Semgrep SAST was consequently enforced NOWHERE while
# .github/PULL_REQUEST_TEMPLATE.md still asked authors to attest it passed
# (found and fixed 2026-09-20).
#
# The rule now: .git/hooks/pre-commit has exactly ONE owner, the pre-commit
# framework. Everything else contributes hooks through .pre-commit-config.yaml.
# This script therefore never overwrites a config and never clobbers a hook it
# did not write. Re-running it as llm_settings grows is safe by construction:
# it adds what is missing, reports what it did not touch, and changes nothing
# else. That is the property that lets you install this into many repos, in
# any order, more than once, without losing work.

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HOOK_SOURCE="$SCRIPT_DIR/pre-commit"
GITLEAKS_CONFIG="$SCRIPT_DIR/gitleaks.toml"
FORCE=0
GLOBAL=0

for arg in "$@"; do
    case "$arg" in
        --global) GLOBAL=1 ;;
        --force)  FORCE=1 ;;
        -h|--help)
            sed -n '3,6p' "${BASH_SOURCE[0]}"; exit 0 ;;
        *) echo "Unknown argument: $arg" >&2; exit 2 ;;
    esac
done

# Baseline hook ids this toolchain expects. Kept inline rather than in a
# separate file so the installer stays self-contained and there is no second
# artifact to drift. Extend this list as llm_settings grows.
BASELINE_HOOK_IDS="gitleaks detect-secrets check-added-large-files detect-private-key detect-aws-credentials check-yaml check-json check-merge-conflict trailing-whitespace end-of-file-fixer"

hook_is_pre_commit() {   # $1 = path to a hook file
    [ -f "$1" ] && grep -q "File generated by pre-commit" "$1" 2>/dev/null
}

backup_path() { echo "$1.pre-llm-settings.$(date +%Y%m%d-%H%M%S)"; }

# ---------------------------------------------------------------------------
# --global: seed the template used by future `git init`
# ---------------------------------------------------------------------------
if [ "$GLOBAL" -eq 1 ]; then
    echo "📦 Setting up global git hooks template..."
    TEMPLATE_DIR="${GIT_TEMPLATE_DIR:-$HOME/.git-templates}"
    HOOKS_DIR="$TEMPLATE_DIR/hooks"
    mkdir -p "$HOOKS_DIR"

    if [ -f "$HOOKS_DIR/pre-commit" ] && ! cmp -s "$HOOK_SOURCE" "$HOOKS_DIR/pre-commit"; then
        if [ "$FORCE" -eq 0 ]; then
            bk="$(backup_path "$HOOKS_DIR/pre-commit")"
            cp "$HOOKS_DIR/pre-commit" "$bk"
            echo "   ℹ️  existing template hook backed up to $bk"
        fi
    fi
    cp "$HOOK_SOURCE" "$HOOKS_DIR/pre-commit"
    chmod +x "$HOOKS_DIR/pre-commit"
    git config --global init.templateDir "$TEMPLATE_DIR"

    echo "✅ Global template configured at $TEMPLATE_DIR"
    echo "   NEW repos get a standalone gitleaks+git-secrets floor."
    echo "   It is superseded the moment a repo runs \`pre-commit install\`,"
    echo "   which is correct — pre-commit is the intended owner."
    exit 0
fi

# ---------------------------------------------------------------------------
# Repo mode
# ---------------------------------------------------------------------------
if [ ! -d ".git" ] && ! git rev-parse --git-dir >/dev/null 2>&1; then
    echo "❌ Error: Not in a git repository" >&2
    echo "" >&2
    echo "Usage:" >&2
    echo "  ./install.sh          # Install to current repo" >&2
    echo "  ./install.sh --global # Seed template for all new repos" >&2
    exit 1
fi

GIT_DIR="$(git rev-parse --git-common-dir 2>/dev/null || echo .git)"
HOOK_PATH="$GIT_DIR/hooks/pre-commit"
CHANGED=0
SKIPPED=0

echo "📦 Installing llm_settings hooks to $(pwd)"
echo ""

# 1. .pre-commit-config.yaml — seed if absent, NEVER modify if present ------
if [ -f ".pre-commit-config.yaml" ]; then
    echo "   ⏭️  .pre-commit-config.yaml exists — left untouched (never overwritten)"
    SKIPPED=$((SKIPPED + 1))
    missing=""
    for id in $BASELINE_HOOK_IDS; do
        grep -qE "^[[:space:]]*-?[[:space:]]*id:[[:space:]]*${id}[[:space:]]*$" \
            .pre-commit-config.yaml 2>/dev/null || missing="$missing $id"
    done
    if [ -n "$missing" ]; then
        echo "   ⚠️  baseline hooks NOT present in this repo's config:"
        for id in $missing; do echo "        - $id"; done
        echo "      Add them yourself if wanted. This script will not edit a"
        echo "      config it did not write — that is how work gets lost."
    else
        echo "   ✅ all baseline hook ids already present"
    fi
else
    cat > .pre-commit-config.yaml <<'BASELINE'
# Seeded by .llm_settings/git-hooks/install.sh
# This file is the single owner of .git/hooks/pre-commit. Add tooling here
# rather than writing the hook file directly.
repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.1
    hooks:
      - id: gitleaks

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=10000']
      - id: detect-private-key
      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer

  # Keep this rev in step with .secrets.baseline's "version" field — an older
  # hook cannot read a newer baseline and aborts, blocking every commit.
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package-lock.json

  - repo: local
    hooks:
      - id: git-secrets
        name: git-secrets (AWS credential patterns)
        entry: git-secrets --pre_commit_hook --
        language: system
        pass_filenames: true
BASELINE
    echo "   ✅ .pre-commit-config.yaml seeded"
    CHANGED=$((CHANGED + 1))
fi

# 2. gitleaks.toml — copy only if absent -----------------------------------
if [ -f "$GITLEAKS_CONFIG" ]; then
    if [ -f "gitleaks.toml" ]; then
        echo "   ⏭️  gitleaks.toml exists — left untouched"
        SKIPPED=$((SKIPPED + 1))
    else
        cp "$GITLEAKS_CONFIG" gitleaks.toml
        echo "   ✅ gitleaks.toml copied"
        CHANGED=$((CHANGED + 1))
    fi
fi

# 3. The hook path — back up anything we did not write, never silently ------
if hook_is_pre_commit "$HOOK_PATH"; then
    echo "   ✅ $HOOK_PATH already owned by pre-commit"
elif [ -f "$HOOK_PATH" ]; then
    bk="$(backup_path "$HOOK_PATH")"
    cp "$HOOK_PATH" "$bk"
    echo "   ℹ️  existing non-pre-commit hook backed up to:"
    echo "        $bk"
    echo "      (pre-commit install below will take ownership; it preserves"
    echo "       the previous hook as pre-commit.legacy and still runs it)"
fi

# 4. Hand ownership to pre-commit ------------------------------------------
if command -v pre-commit &>/dev/null; then
    if pre-commit install >/dev/null 2>&1; then
        echo "   ✅ pre-commit installed as the hook owner"
        CHANGED=$((CHANGED + 1))
    else
        echo "   ❌ \`pre-commit install\` failed — hooks are NOT active" >&2
        exit 1
    fi
else
    echo "   ❌ pre-commit not found — hooks are NOT active." >&2
    echo "      Provision via Nix (this repo ships it in flake.nix devTools):" >&2
    echo "        nix develop          # or: nix profile install nixpkgs#pre-commit" >&2
    echo "      Then re-run this script. Refusing to fall back to copying a" >&2
    echo "      standalone hook: that is what silently displaced the real" >&2
    echo "      hook chain before." >&2
    exit 1
fi

# 5. Report the delta, and prove the hooks actually run ---------------------
echo ""
echo "🔍 Verifying the hook chain actually executes..."
if pre-commit run --hook-stage pre-commit --all-files --dry-run >/dev/null 2>&1 \
   || pre-commit run gitleaks --files "$0" >/dev/null 2>&1; then
    echo "   ✅ hooks execute"
else
    echo "   ⚠️  could not confirm execution — run \`pre-commit run --all-files\` manually"
fi

echo ""
echo "📊 Summary: ${CHANGED} change(s) applied, ${SKIPPED} existing file(s) left untouched."
echo "   Re-running this script is safe; it only ever adds what is missing."

echo ""
echo "🔍 Checking for required tools..."
for tool in gitleaks git-secrets semgrep; do
    if command -v "$tool" &>/dev/null; then
        echo "   ✅ $tool"
    else
        echo "   ⚠️  $tool missing — nix profile install nixpkgs#$tool"
    fi
done
